-- READ-ONLY. GENERATED by test/support/functionCatalog.mjs — do not edit by hand
-- (test/production-drift-repair-db.test.js fails if this file is stale).
--
-- For each function the 2026-10-08 production repair touches, reports which
-- repository file(s) define the exact body production is running, by md5 of
-- pg_proc.prosrc. "NOT PRESENT" = the function does not exist.
-- "NO REPOSITORY MATCH" = production runs a body that no repository file
-- defines (a hand edit or unrecorded change): stop and review before
-- replacing it. Output is schema metadata only — no user data.
with repository(name, source_file, body_md5) as (
  values
    ('handle_new_user', 'schema.sql', '8247e90643d29740f9f85333aedbf764'),
    ('preview_invitation', 'schema.sql', '1939458135533ca76edfc2970863e61d'),
    ('accept_invitation', 'schema.sql', '4dc8643623909134bfe8f903477dbbad'),
    ('resolve_cobuyer_compare_perspectives', 'schema.sql', '5b3a3b795ef7fec66ba93409d25d7675'),
    ('resolve_collaborator_search_context', 'schema.sql', '4be044feecfb588616a21add6e159eda'),
    ('resolve_cobuyer_compare_perspectives', 'schema.sql', 'bbe2d68d428207e631c3ec19f323badb'),
    ('resolve_collaborator_search_context', 'schema.sql', '0575d0e36b126bb5c5043b172dab3df6'),
    ('preview_invitation', 'schema.sql', 'f9f0ee8004eb4b4a12a0bf5453d69bd0'),
    ('accept_invitation', 'schema.sql', '1091b8701842bd03fdbc032b76e0f09f'),
    ('get_realtor_client_roster', 'schema.sql', '7fc441ad52ceac81a80e1605f75f3d99'),
    ('create_realtor_suggestion', 'schema.sql', 'd4b0ac83709d201dad00c054c733144d'),
    ('save_realtor_note', 'schema.sql', '88333583fffea6485326c25c5255f796'),
    ('suggest_home_tour', 'schema.sql', 'ce6c16e9826b54d2438baaf35f668746'),
    ('create_buyer_invitation', 'schema.sql', '37500d0173d46bf45cfb52176166ca80'),
    ('preview_invitation', 'schema.sql', '5288a511833d73e2afa4beeecba333ea'),
    ('accept_invitation', 'schema.sql', 'ed627e0715413f70c155646020c0d16c'),
    ('create_prospective_search', 'schema.sql', 'b290b1edcd519f4abccc6a5703108b34'),
    ('invite_prospective_client', 'schema.sql', '816bdefb50af4b74b6e0e83d07a070bd'),
    ('create_buyer_invitation', 'schema.sql', 'f1d1d8dec5ad2630ab65a91d0edcbe75'),
    ('preview_invitation', 'schema.sql', '472ce27b97c79d536808272e73f1e0de'),
    ('claim_prospective_search', 'schema.sql', 'f561b83b16aa80be2318e14d30007a17'),
    ('accept_invitation', 'schema.sql', '539fc5bffc2077470d5c8a73ebd1f34e'),
    ('preview_invitation', 'migrations/2026-09-05-cobuyer-phase-d-invitations.sql', '1939458135533ca76edfc2970863e61d'),
    ('accept_invitation', 'migrations/2026-09-05-cobuyer-phase-d-invitations.sql', '7a5797919a0c8496e8be04252700c98c'),
    ('resolve_cobuyer_compare_perspectives', 'migrations/2026-09-08-fix-compare-bedroom-location-type.sql', '6ce961e577d63a42fe4f96a7e02319ce'),
    ('resolve_cobuyer_compare_perspectives', 'migrations/2026-09-08-secure-compare-perspectives.sql', '6ce961e577d63a42fe4f96a7e02319ce'),
    ('resolve_cobuyer_compare_perspectives', 'migrations/2026-09-09-rental-v1-shared-facts.sql', 'eea824396ba4dfbb6512564db20aaefd'),
    ('resolve_collaborator_search_context', 'migrations/2026-09-10-shared-search-collaboration-contract.sql', '4be044feecfb588616a21add6e159eda'),
    ('resolve_collaborator_search_context', 'migrations/2026-09-16-map-collaborator-places.sql', '1ddf5fefe48b83e67632e7f3afd9d521'),
    ('resolve_collaborator_search_context', 'migrations/2026-09-16-my-search-collaborator-display-name.sql', 'a4c7014ba55e6aadb1b9c8d06b5e41e0'),
    ('save_realtor_note', 'migrations/2026-09-16-realtor-notes-tours-buyer-invitations.sql', '88333583fffea6485326c25c5255f796'),
    ('suggest_home_tour', 'migrations/2026-09-16-realtor-notes-tours-buyer-invitations.sql', 'ce6c16e9826b54d2438baaf35f668746'),
    ('create_buyer_invitation', 'migrations/2026-09-16-realtor-notes-tours-buyer-invitations.sql', '37500d0173d46bf45cfb52176166ca80'),
    ('preview_invitation', 'migrations/2026-09-16-realtor-notes-tours-buyer-invitations.sql', '5288a511833d73e2afa4beeecba333ea'),
    ('accept_invitation', 'migrations/2026-09-16-realtor-notes-tours-buyer-invitations.sql', '07ae0e8da5a86eeb0f61fea36ba54919'),
    ('resolve_cobuyer_compare_perspectives', 'migrations/2026-09-16-realtor-role-foundation.sql', 'b22f5c5ff9b3780de761266d9b84622c'),
    ('resolve_collaborator_search_context', 'migrations/2026-09-16-realtor-role-foundation.sql', '0575d0e36b126bb5c5043b172dab3df6'),
    ('preview_invitation', 'migrations/2026-09-16-realtor-role-foundation.sql', 'f9f0ee8004eb4b4a12a0bf5453d69bd0'),
    ('accept_invitation', 'migrations/2026-09-16-realtor-role-foundation.sql', '1091b8701842bd03fdbc032b76e0f09f'),
    ('get_realtor_client_roster', 'migrations/2026-09-16-realtor-search-view.sql', '4a6c00413a6a218602da54acff46bb17'),
    ('create_prospective_search', 'migrations/2026-09-16-realtor-started-searches.sql', 'b290b1edcd519f4abccc6a5703108b34'),
    ('invite_prospective_client', 'migrations/2026-09-16-realtor-started-searches.sql', '816bdefb50af4b74b6e0e83d07a070bd'),
    ('create_buyer_invitation', 'migrations/2026-09-16-realtor-started-searches.sql', 'f1d1d8dec5ad2630ab65a91d0edcbe75'),
    ('preview_invitation', 'migrations/2026-09-16-realtor-started-searches.sql', '472ce27b97c79d536808272e73f1e0de'),
    ('claim_prospective_search', 'migrations/2026-09-16-realtor-started-searches.sql', '9b827b37bee5dbef8dba39250c5fe847'),
    ('accept_invitation', 'migrations/2026-09-16-realtor-started-searches.sql', '853b7898756904864988b91087894a4b'),
    ('create_realtor_suggestion', 'migrations/2026-09-16-realtor-suggestions.sql', 'd4b0ac83709d201dad00c054c733144d'),
    ('resolve_cobuyer_compare_perspectives', 'migrations/2026-09-18-tour-evaluations.sql', 'bbe2d68d428207e631c3ec19f323badb'),
    ('handle_new_user', 'migrations/2026-09-19-account-name-capture-and-realtor-home.sql', '5da444dcc7d937038fb3b2184f5fcc0f'),
    ('resolve_display_name', 'migrations/2026-09-19-account-name-capture-and-realtor-home.sql', '9d27205dea220530d1a160c83deece6f'),
    ('get_realtor_client_roster', 'migrations/2026-09-19-account-name-capture-and-realtor-home.sql', '7e228ae18281ad12b1f4d198d53c8a28'),
    ('create_realtor_suggestion', 'migrations/2026-09-19-account-name-capture-and-realtor-home.sql', '38dc64a99a1441c3470a4d4d48526170'),
    ('save_realtor_note', 'migrations/2026-09-19-account-name-capture-and-realtor-home.sql', '72b4967e36519d4d5b820e78c08f34b3'),
    ('suggest_home_tour', 'migrations/2026-09-19-account-name-capture-and-realtor-home.sql', 'e48d2646a189016c7a046c637dd5e3ac'),
    ('invite_prospective_client', 'migrations/2026-09-19-account-name-capture-and-realtor-home.sql', '3199b9c8925cb34ce8eefc2c6a6c39df'),
    ('resolve_collaborator_search_context', 'migrations/2026-09-19-account-name-capture-and-realtor-home.sql', '847645588e11b51766f0bb404c06e88a'),
    ('create_realtor_connection_request', 'migrations/2026-09-19-account-name-capture-and-realtor-home.sql', 'af526da3fa026524b92af4b8337f3168'),
    ('preview_invitation', 'migrations/2026-09-19-account-name-capture-and-realtor-home.sql', '0a62f54eb4977c918b7103666b16bd82'),
    ('resolve_cobuyer_compare_perspectives', 'migrations/2026-10-07-cobuyer-compare-garage-parity.sql', '960d7123231eb983709350e11602b6f9'),
    ('claim_prospective_search', 'migrations/2026-10-07-invitation-acceptance-conflict-targets.sql', 'f561b83b16aa80be2318e14d30007a17'),
    ('accept_invitation', 'migrations/2026-10-07-invitation-acceptance-conflict-targets.sql', '539fc5bffc2077470d5c8a73ebd1f34e'),
    ('resolve_collaborator_search_context', 'migrations/2026-10-08-collaborator-context-return-type.sql', 'a4c7014ba55e6aadb1b9c8d06b5e41e0')
),
wanted(name) as (values ('accept_invitation'), ('claim_prospective_search'), ('create_buyer_invitation'), ('create_prospective_search'), ('create_realtor_connection_request'), ('create_realtor_suggestion'), ('get_realtor_client_roster'), ('handle_new_user'), ('invite_prospective_client'), ('preview_invitation'), ('resolve_cobuyer_compare_perspectives'), ('resolve_collaborator_search_context'), ('resolve_display_name'), ('save_realtor_note'), ('suggest_home_tour')),
production as (
  select p.proname as name,
         md5(p.prosrc) as body_md5,
         md5(replace(p.prosrc, chr(13), '')) as body_md5_lf,
         pg_get_function_identity_arguments(p.oid) as args,
         pg_get_function_result(p.oid) as result
  from pg_proc p
  where p.pronamespace = 'public'::regnamespace
)
select w.name,
       coalesce(p.args, '') as arguments,
       case
         when p.name is null then 'NOT PRESENT'
         when not exists (select 1 from repository r where r.name = w.name and r.body_md5 in (p.body_md5, p.body_md5_lf)) then 'NO REPOSITORY MATCH'
         else (select string_agg(r.source_file, ', ' order by r.source_file) from repository r
               where r.name = w.name and r.body_md5 in (p.body_md5, p.body_md5_lf))
       end as production_matches
from wanted w
left join production p on p.name = w.name
order by w.name, p.args;
