// Catalog of every public function body the repository has ever defined
// (schema.sql + migrations), keyed by md5 of the body exactly as Postgres
// stores it in pg_proc.prosrc. Used to generate
// supabase/production-function-fingerprints.sql, which tells an operator
// precisely which repository version of each function production runs.
import { createHash } from 'node:crypto';
import { readdirSync, readFileSync } from 'node:fs';

const ROOT = new URL('../../supabase/', import.meta.url);

// Functions the 2026-10-08 production repair replaces or depends on.
export const REPAIR_FUNCTIONS = Object.freeze([
  'accept_invitation', 'claim_prospective_search', 'create_buyer_invitation', 'create_prospective_search',
  'create_realtor_connection_request', 'create_realtor_suggestion', 'get_realtor_client_roster', 'handle_new_user',
  'invite_prospective_client', 'preview_invitation', 'resolve_cobuyer_compare_perspectives',
  'resolve_collaborator_search_context', 'resolve_display_name', 'save_realtor_note', 'suggest_home_tour',
]);

const DEFINITION = /create\s+(?:or\s+replace\s+)?function\s+public\.([a-z_]+)\s*\([\s\S]*?\bas\s+\$([a-z_]*)\$([\s\S]*?)\$\2\$/gi;

export function functionCatalog() {
  const files = ['schema.sql', ...readdirSync(new URL('migrations/', ROOT)).sort().map((file) => `migrations/${file}`)];
  const rows = [];
  for (const file of files) {
    const sql = readFileSync(new URL(file, ROOT), 'utf8');
    for (const match of sql.matchAll(DEFINITION)) {
      rows.push({ name: match[1], file, md5: createHash('md5').update(match[3]).digest('hex') });
    }
  }
  return rows;
}

export function fingerprintSql(names = REPAIR_FUNCTIONS) {
  const catalog = functionCatalog().filter((row) => names.includes(row.name));
  const values = catalog.map((row) => `    ('${row.name}', '${row.file}', '${row.md5}')`).join(',\n');
  const wanted = names.map((name) => `('${name}')`).join(', ');
  return `-- READ-ONLY. GENERATED by test/support/functionCatalog.mjs — do not edit by hand
-- (test/production-drift-repair-db.test.js fails if this file is stale).
--
-- For each function the 2026-10-08 production repair touches, reports which
-- repository file(s) define the exact body production is running, by md5 of
-- pg_proc.prosrc. "NOT PRESENT" = the function does not exist.
-- "NO REPOSITORY MATCH" = production runs a body that no repository file
-- defines (a hand edit or unrecorded change): stop and review before
-- replacing it. Output is schema metadata only — no user data.
with repository(name, source_file, body_md5) as (
  values
${values}
),
wanted(name) as (values ${wanted}),
production as (
  select p.proname as name,
         md5(p.prosrc) as body_md5,
         md5(replace(p.prosrc, chr(13), '')) as body_md5_lf,
         pg_get_function_identity_arguments(p.oid) as args,
         pg_get_function_result(p.oid) as result
  from pg_proc p
  where p.pronamespace = 'public'::regnamespace
)
select w.name,
       coalesce(p.args, '') as arguments,
       case
         when p.name is null then 'NOT PRESENT'
         when not exists (select 1 from repository r where r.name = w.name and r.body_md5 in (p.body_md5, p.body_md5_lf)) then 'NO REPOSITORY MATCH'
         else (select string_agg(r.source_file, ', ' order by r.source_file) from repository r
               where r.name = w.name and r.body_md5 in (p.body_md5, p.body_md5_lf))
       end as production_matches
from wanted w
left join production p on p.name = w.name
order by w.name, p.args;
`;
}
